name: invent_app_redesign
description: A redesigned Flutter inventory app using local storage.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  google_fonts: ^6.2.1
  connectivity_plus: ^5.0.2
  mobile_scanner: ^3.5.4 
  image_picker: ^1.0.0
  firebase_storage: ^11.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.1
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.0.11
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  animations: ^2.0.7
  flutter_secure_storage: ^9.2.2
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/barcode_icon.png
    - assets/images/empty_box.png
    - assets/icon/app_icon.png